### ISSUE TITLE
this.listName must not have parenthesis

### ISSUE THREAD

**Issue by rowild** [danwellman/to-do#1]
Hi,

while working through your excellent tutorial in RequireJS that you did for tutsplus, I realize, that your script here on github are different from the video tutorial.

in view_models/app.js and view_models/list.js, there is an attribute called 'this.isButtonEnabled'. The if-statement in their respective functions test against

```
this.isButtonEnabled = ko.computed(function () {
    if (this.listName()...
```

[app.js, around line 20]

and

```
this.isButtonEnabled = ko.computed(function () {
    if (this.taskName()...
```

[list.js, around line 14]

respectively, where the parenthesis after listName and taskName must be removed.
At the moment this error leads to not-working 'Add List' / 'Add Task' buttons.

I'll report back once I finished the tutorial, which is - I need to say it again - really, really awesome!!! Thank you so much!

**Comment by danwellman** [comment]
Hey, thanks for raising this, I'll take a look asap

**Comment by danwellman** [comment]
I took at look at both the lesson as well as the code for this issue, the lesson shows the `.isButtonEnabled` method in both the app and list viewModels as they appear in the app.js and list.js viewModel files in the repository.

As the `listName` and 'taskName' properties are Knockout observables as opposed to simple object accessors, the value is returned using parentheses.

This is working as expected and the syntax is correct. What may not be so clear in the video is that the buttons for adding new lists and new tasks do not become enabled until you have tabbed away from the associated input field

**Comment by rowild** [comment]
A-haaaa! I understand now! Tabbing away it is!
Thanks for clearing that up for me :-)

**Comment by danwellman** [comment]
No problem, I should have made this clearer in the video
