### ISSUE TITLE
wrong uiString in list.js

### ISSUE THREAD

**Issue by rowild** [danwellman/to-do#2]
The list.js viewModel uses this 

```
function ListViewModel() {
        this.placeholderText = uiStrings.placeholderText;
```

for a placeholder text. To differentiate between the placeholder text for a new list and a new task, this should be used (the video tutorial shows, how that line is created, but eventually uses the wrong placeholder text):

```
function ListViewModel() {
        this.placeholderText = uiStrings.createTaskPlaceholderText;
```

**Comment by danwellman** [comment]
Thanks for raising this, let me just clarify the issue; during the video is the `placeholderText` property in the list.js viewModel changed from `uiStrings.createTaskPlaceholderText` to `uiStrings.placeholderText` at some point in the video?

The app.js viewModel also contains a `placeholderText` property, and this one does have the value `uiStrings.placeholderText`

**Comment by rowild** [comment]
Looking at this issue again, I have no idea what happened yesterday. Maybe I way too tired... however, I am very sorry for wasting your time here. Everything is ok here, in the video and the scritps! My appologies!
Can this issue be deleted as a whole?

**Comment by danwellman** [comment]
No problem, I'm always happy to have a discussion about a potential issue, even if it turns out not to be an issue :)

Issues cannot be deleted I'm afraid

**Comment by rowild** [comment]
I'm glad you see it that way - thank you :-)
